# Generated by Django 5.2.7 on 2025-10-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='laptops/'),
        ),
    ]
