# Generated by Django 5.2.7 on 2025-10-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0002_laptop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='category',
            field=models.CharField(choices=[('entry', 'Entry Level'), ('mid', 'Mid End'), ('high', 'High End')], default='entry', max_length=10),
        ),
    ]
