# Generated by Django 5.2.7 on 2025-10-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0003_laptop_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
